# Generated by Django 4.1.10 on 2023-09-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_files/'),
        ),
    ]
