# Generated by Django 4.1.10 on 2023-09-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_course', '0002_lesson_lesson_file_quiz_quiz_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_file',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_file',
        ),
    ]
