# Generated by Django 4.1.10 on 2023-09-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_course', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
